general.import = [ "~/.config/alacritty/colors.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
size = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

